import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Compass, Plus } from "lucide-react";
import { SiteHeader } from "@/components/site-header";

const expertise = [
  { title: "Meticulous world-building", text: "A fictional universe needs more than a map. We establish the rules behind every element so your world feels coherent across an entire saga.", points: [["Geography & cartography", "Continents, biomes, borders, trade routes, and the strategic importance of place."], ["Magic & cosmology", "The sources of magic, its limits and costs, and its place in the wider order."], ["History & culture", "Detailed timelines, foundational myths, religions, languages, and the customs of different races and kingdoms."]] },
  { title: "The political & military engine", text: "Large-scale conflicts need clear motivations and believable consequences. We connect the struggle for power to the people living through it.", points: [["Complex factionalism", "Political intrigue among kingdoms, guilds, religious orders, and rival species, woven into a clear narrative."], ["Battle strategy", "Cinematic battles and military movements that reflect the technology and magic of your world."]] },
  { title: "Character & prophecy", text: "The emotional heart of an epic must never disappear beneath its scale. The reluctant hero, flawed king, or cynical wizard gives the reader someone to follow.", points: [["Distinct personal journeys", "Arcs for every major viewpoint character, with motivations and choices that shape the story."], ["A world and its people", "Personal stakes intertwined with ancient prophecies, dynastic struggles, and the fate of the realm."]] },
];
const steps = [
  ["Grand vision & lore", "Interviews and workshops draw out your vision. Together, we develop a World Bible and Lore Document: a shared reference for history, geography, cultures, and the laws of magic that helps prevent inconsistencies."],
  ["The series blueprint", "We plan beyond the first book, mapping major plot points, character development, and series-ending payoffs across at least the first three books. This gives the opening novel a clear role in a longer journey."],
  ["Drafting & immersion", "Your manuscript takes shape in milestones, with descriptive prose, immersive settings, and escalating stakes. We balance exposition with active plotting to sustain momentum across the novel’s length."],
  ["Rigorous quality assurance", "A lore consistency check and multiple rounds of developmental and copy editing refine the manuscript. We review the story’s internal rules, character arcs, and prose as one coherent whole."],
];
const faqs = [
  ["What is the typical fee for your epic fantasy ghostwriting services?", "Epic fantasy requires substantial world-building and a longer manuscript. Professional projects typically begin around $50,000 USD and can exceed $120,000 USD, depending on lore development, viewpoint characters, and the required series mapping. Your detailed proposal sets out the scope and payment schedule before work begins."],
  ["How long will it take to complete a full heroic fantasy novel?", "A high-quality epic or high fantasy novel typically takes 6 to 10 months. This allows time to develop the initial world-building, outline the plot carefully, draft an expansive manuscript, and complete consistency and quality reviews."],
  ["How do you handle the technical complexity of my magic system?", "We create a specialized Magic System Guide within the Lore Document, detailing rules, limitations, and costs. The writer uses this guide to avoid convenient fixes that break the world’s established logic and the reader’s belief."],
  ["Can your ghostwriter help me develop a series, not just a single book?", "Yes. Series architecture is central to the process. We map the narrative structure for at least three books so the first installment establishes the mysteries, conflicts, and character arcs that carry through the entire saga."],
  ["Do you use specialized fantasy novel writers who understand older tropes, such as Tolkien and Jordan?", "Our writers work with classic and modern fantasy traditions. Whether your story draws on grand quests or the morally complex political intrigue of modern grimdark, we match the approach to the voice and structural demands of your book."],
  ["Who retains the rights and royalties for the epic fantasy novel?", "You retain 100% of the rights, copyright, and royalties. Compensation for our ghostwriting services is the project fee outlined in your agreement."],
  ["What level of detail do I need to provide before starting Phase I?", "A compelling core concept is enough—for example, a failed general uniting warring peoples against an ancient rising god. The process turns your idea into a fuller universe. If you already have extensive notes, we build from them; if not, we help develop the world with you."],
];

export function EpicFantasyPage() {
  return (
    <main>
      <SiteHeader />
      <section className="innerHero historicalRomanceHero epicFantasyHero" aria-labelledby="epic-fantasy-title">
        <Image className="historicalRomanceImage" src="/images/epic-high-fantasy-hero.png" alt="" fill sizes="100vw" preload />
        <div className="historicalRomanceCopy">
          <p className="eyebrow">Epic & high fantasy ghostwriting</p>
          <h1 id="epic-fantasy-title">Best Writers for Epic Fantasy Ghostwriting and High Fantasy Novel Creation</h1>
          <p>A vast world. An unforgettable journey. Turn your vision into an immersive saga with the characters, lore, and ambition to carry readers from the first chapter to the final battle.</p>
          <Link className="button" href="/contact">Begin your saga <ArrowRight size={18} /></Link>
        </div>
      </section>
      <section className="pagePromise">{["Immersive world-building", "Confidential collaboration", "Your story. Your rights."].map(text => <p key={text}><Check size={16} />{text}</p>)}</section>
      <div className="romanceContent">
        <section className="romanceIntro romanceWrap" aria-labelledby="epic-intro-title">
          <div><p className="eyebrow">Crafting the vast and the grand</p><h2 id="epic-intro-title">Specialized epic fantasy<br /><em>ghostwriting services.</em></h2><p className="romanceLead">Got a massive, multi-volume fantasy saga brewing? Let’s build your legacy.</p><p>Epic fantasy calls for a writer who is also an architect of worlds, a chronicler of ancient histories, and a strategist capable of managing vast casts, political systems, and conflicts spanning generations.</p><p>At Storybound House, we bring those elements together around your vision. Whether it begins with a sweeping conflict over a divine artifact, a dynastic struggle for a throne, or a journey to fulfill an ancient prophecy, we help shape it into a cohesive, professionally developed manuscript.</p><Link className="fictionTextLink" href="/contact">Tell us about your world <ArrowRight size={17} /></Link></div>
          <aside className="romanceCraft"><Compass size={30} strokeWidth={1.3} aria-hidden="true" /><p className="eyebrow">An extraordinary world, built to last</p><h3>Scale with purpose.<br />Wonder with consistency.</h3>{[["A shared lore reference", "One foundation for history, geography, magic, and culture."], ["A vision beyond one volume", "A series structure that connects the first book to the larger story."], ["An emotional center", "Characters whose personal journeys matter as much as the fate of the world."]].map(([title, text]) => <div className="romanceCraftPoint" key={title}><Check size={18} /><div><h4>{title}</h4><p>{text}</p></div></div>)}</aside>
        </section>
        <section className="romanceSpecialties" aria-labelledby="epic-expertise-title"><div className="romanceWrap"><div className="romanceSectionHeading"><p className="eyebrow">The expertise behind the epic</p><h2 id="epic-expertise-title">The craft of a high fantasy novel ghostwriter.</h2><p>Scale and consistency are the central challenges. A systematic approach keeps your world’s logic, lore, and narrative momentum aligned.</p></div><div className="epicExpertiseGrid">{expertise.map(({ title, text, points }, index) => <article key={title}><span className="epicChapter">0{index + 1}</span><h3>{title}</h3><p>{text}</p><dl>{points.map(([label, detail]) => <div key={label}><dt>{label}</dt><dd>{detail}</dd></div>)}</dl></article>)}</div></div></section>
        <section className="romanceProcess romanceWrap" aria-labelledby="epic-process-title"><div className="romanceSectionHeading"><p className="eyebrow">A transparent creative partnership</p><h2 id="epic-process-title">The collaborative process:<br /><em>from grand vision to final draft.</em></h2><p>Work closely with your ghostwriter through four clearly defined stages, with your vision guiding the story throughout.</p></div><ol className="romanceSteps">{steps.map(([title, text], index) => <li key={title}><span className="romanceStepNumber">0{index + 1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
        <section className="romanceInvestment romanceWrap" aria-labelledby="epic-investment-title"><div><p className="eyebrow">Investment in a legacy</p><h2 id="epic-investment-title">The value of<br /><em>specialized ghostwriting.</em></h2><p>Epic fantasy asks for substantial planning before the first chapter. The investment reflects the time and skill needed to create a coherent world, a compelling long-form narrative, and a foundation for future books.</p><p>Transparent pricing follows the agreed scope, including world-building, outlining, writing, and editing. Your proposal makes the work, milestones, and deliverables clear before the project begins.</p><Link className="button" href="/contact">Discuss your project <ArrowRight size={17} /></Link></div><div className="romanceScope"><h3>A foundation for your entire universe</h3><ul>{["World Bible and Lore Document", "Magic-system rules, limits, and costs", "Multi-book plotting and viewpoint arcs", "Milestone drafts and collaborative reviews", "Lore consistency and editorial refinement"].map(text => <li key={text}><Check size={18} />{text}</li>)}</ul></div></section>
        <section className="romanceFaq romanceWrap" aria-labelledby="epic-faq-title"><div><p className="eyebrow">Frequently asked questions</p><h2 id="epic-faq-title">An ambitious story.<br /><em>A clear way forward.</em></h2><p>Practical answers about engaging an epic fantasy ghostwriter, from your first idea to a finished manuscript.</p></div><div className="romanceQuestions">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<Plus size={18} aria-hidden="true" /></summary><p>{answer}</p></details>)}</div></section>
        <section className="romanceClosing"><p className="eyebrow">From your imagination to the page</p><h2>Ready to begin your saga?</h2><p>Bring your grand vision. We’ll help give it the structure, detail, and evocative prose it deserves.</p><Link className="button" href="/contact">Let’s build your world <ArrowRight size={17} /></Link></section>
      </div>
    </main>
  );
}
