import Link from "next/link";
import { ArrowRight, Check, Compass, Plus } from "lucide-react";

const specialties = [
  ["01", "Epic & high fantasy", "Expansive worlds, ancient histories, political tensions, and interconnected character journeys that give a large-scale story its shape."],
  ["02", "Urban fantasy", "Hidden magic and extraordinary beings woven into recognizable modern settings, with atmosphere and momentum working together."],
  ["03", "Dark fantasy & grimdark", "Unforgiving worlds, difficult choices, and morally complex characters whose actions carry meaningful consequences."],
  ["04", "Young adult fantasy", "Coming-of-age journeys driven by identity, belonging, and discovery, with accessible world-building and a strong character voice."],
  ["05", "Military & quest fantasy", "Campaigns, alliances, perilous journeys, and competing loyalties, balanced with the personal stakes behind the larger conflict."],
];
const steps = [
  ["Establish the world", "We explore your vision and develop a shared lore reference covering the geography, history, cultures, and magic your story needs. You review this foundation before the manuscript takes shape."],
  ["Map the story", "An outline connects character arcs, major turning points, and changes in viewpoint. For a series, we consider the wider journey while giving the first book a purposeful structure of its own."],
  ["Write the adventure", "The draft develops in stages, blending sensory detail, distinct voices, and action. Your feedback on early chapters helps guide the tone, exposition, and pacing throughout the manuscript."],
  ["Refine and review", "Revision strengthens the prose, character development, and narrative flow. We check the world’s rules and timeline for consistency, with editorial support agreed in your project scope."],
];
const faqs = [
  ["How much does fantasy ghostwriting cost?", "The proposal depends on the manuscript length, world-building requirements, number of viewpoints, existing material, and editorial support you need. Storybound House prepares a tailored scope with clear deliverables and payment terms after discussing your project."],
  ["How long does it take to complete a fantasy novel?", "World-building, outlining, drafting, and revision each need time. We agree a schedule around your book’s length, complexity, and your availability for feedback. An expansive setting or a multi-book plan may require additional development."],
  ["How do you find the right voice for my story?", "We discuss your preferred style, themes, characters, and any writing samples you have. The creative fit comes from understanding the narrative you want to tell, with chapter reviews giving you opportunities to refine the voice as we work."],
  ["How do you develop the world and magic system?", "We create a shared reference for the history, geography, cultures, and magical rules relevant to your story. Abilities, limits, and consequences guide the plot. If the world evolves during drafting, we review and update those decisions together to preserve continuity."],
  ["Can the project work for a self-published author?", "Yes. We discuss your publishing plans, budget, and priorities, then define the development, writing, and editorial support that fits the agreed scope. A clear proposal helps you assess the investment before beginning."],
  ["Who owns the finished fantasy novel?", "The manuscript is developed for you to publish under your name. Ownership, confidentiality, and the handover of project materials are set out in your agreement so you can review the terms before work starts."],
  ["Can you help turn my idea into a series?", "Yes. We can map the larger conflict, recurring characters, and future story threads alongside the first book. A series reference helps track continuity while giving each installment its own character development and satisfying narrative arc."],
];

export function FantasyOverview() {
  return (
    <div className="romanceContent">
      <section className="romanceIntro romanceWrap" aria-labelledby="fantasy-intro-title"><div><p className="eyebrow">Your imagination. A world of possibility.</p><h2 id="fantasy-intro-title">Build a world.<br /><em>Tell a story that belongs in it.</em></h2><p className="romanceLead">A remarkable fantasy invites readers somewhere new—and gives them a reason to stay.</p><p>At Storybound House, we help transform ambitious ideas into immersive fiction. From a hidden magical city to a kingdom on the edge of war, we bring the setting, characters, and plot together around your creative vision.</p><p>The scale can be epic, but the story still needs an emotional center. We work with you to develop believable motivations, purposeful conflicts, and a narrative that makes the world’s wonders matter to its people.</p><Link className="fictionTextLink" href="/contact">Tell us about your fantasy world <ArrowRight size={17} /></Link></div><aside className="romanceCraft"><Compass size={30} strokeWidth={1.3} aria-hidden="true" /><p className="eyebrow">The foundations of great fantasy</p><h3>Wonder with structure.<br />Adventure with meaning.</h3>{[["A world that holds together", "Geography, cultures, and histories that follow a coherent internal logic."], ["Magic with consequences", "Clear expectations, limitations, and costs that support the story’s stakes."], ["Pacing across the bigger picture", "Character arcs and viewpoints that sustain momentum without losing the emotional thread."]].map(([title, text]) => <div className="romanceCraftPoint" key={title}><Check size={18} aria-hidden="true" /><div><h4>{title}</h4><p>{text}</p></div></div>)}</aside></section>

      <section className="romanceSpecialties" aria-labelledby="fantasy-specialties-title"><div className="romanceWrap"><div className="romanceSectionHeading"><p className="eyebrow">Across the fantasy spectrum</p><h2 id="fantasy-specialties-title">Every world has its own kind of wonder.</h2><p>Your setting, audience, and tone guide how we develop the story—from intimate discoveries to sweeping conflicts.</p></div><div className="historicalEraGrid">{specialties.map(([number, title, text]) => <article key={title}><span aria-hidden="true">{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="romanceProcess romanceWrap" aria-labelledby="fantasy-process-title"><div className="romanceSectionHeading"><p className="eyebrow">From lore to the last chapter</p><h2 id="fantasy-process-title">A clear process for<br />an extraordinary vision.</h2><p>We establish the foundations first, then develop the narrative with your feedback at every important stage.</p></div><ol className="romanceSteps">{steps.map(([title, text], index) => <li key={title}><span className="romanceStepNumber" aria-hidden="true">0{index + 1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>

      <section className="historicalReader romanceWrap" aria-labelledby="fantasy-voice-title"><div><p className="eyebrow">A partnership shaped around your voice</p><h2 id="fantasy-voice-title">An epic is only as compelling<br /><em>as the people within it.</em></h2></div><div><p>Political intrigue, intimate character journeys, and sweeping adventures all ask for different storytelling choices. We begin with the themes, tone, and perspective you want your book to carry.</p><p>Through conversations and chapter reviews, we develop a voice that supports your vision. The goal is a manuscript that feels cohesive in scale, rich in character, and recognizably yours.</p></div></section>

      <section className="romanceInvestment romanceWrap" aria-labelledby="fantasy-investment-title"><div><p className="eyebrow">A considered investment in your story</p><h2 id="fantasy-investment-title">Room for ambition.<br /><em>Clarity about the work.</em></h2><p>Fantasy can involve substantial development before the first chapter. Your proposal accounts for the world-building, narrative complexity, writing, and revision your manuscript needs, with a scope you can review before beginning.</p><Link className="button" href="/contact">Discuss your fantasy novel <ArrowRight size={17} /></Link></div><div className="romanceScope"><h3>What we’ll plan together</h3><ul>{["Lore, research, and magic-system development", "Target length, viewpoints, and character arcs", "Standalone or series planning", "Draft reviews and editorial support", "Timeline, payment, confidentiality, and ownership terms"].map(text => <li key={text}><Check size={18} aria-hidden="true" />{text}</li>)}</ul></div></section>

      <section className="romanceFaq romanceWrap" aria-labelledby="fantasy-faq-title"><div><p className="eyebrow">Before the adventure begins</p><h2 id="fantasy-faq-title">Big ideas.<br /><em>Practical answers.</em></h2><p>A few things to know about developing your fantasy novel with Storybound House.</p></div><div className="romanceQuestions">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<Plus size={18} aria-hidden="true" /></summary><p>{answer}</p></details>)}</div></section>
      <section className="romanceClosing"><p className="eyebrow">Your world is waiting</p><h2>Turn the world in your mind into a story on the page.</h2><p>Bring your map, your characters, or a single extraordinary idea.</p><Link className="button" href="/contact">Let’s begin your adventure <ArrowRight size={17} /></Link></section>
    </div>
  );
}
