import Link from "next/link";
import { ArrowRight, Check, Feather, Plus } from "lucide-react";

const eras = [
  ["01", "Regency romance", "Ballrooms, reputation, and the social expectations of early nineteenth-century England give attraction something to push against."],
  ["02", "Victorian romance", "Class, propriety, and a changing society shape intimate stories of longing, independence, and belonging."],
  ["03", "Medieval & Highland romance", "Castles, loyalties, and divided communities create a rich backdrop for love tested by duty and danger."],
  ["04", "Western historical romance", "Frontier communities, uncertain journeys, and the search for a home bring resilience and connection to the page."],
  ["05", "Wartime romance", "Separation, sacrifice, and hope lend emotional weight to relationships set against the upheaval of the World War eras."],
];
const process = [
  ["Research the world", "We begin with the year, location, and circumstances of your characters. Research into everyday life, clothing, social customs, and the conflicts of the period helps establish a convincing foundation."],
  ["Outline history and heart", "Together, we map the relationship alongside the realities of its setting. Attraction, obstacles, turning points, and the ending form an outline for you to review before drafting begins."],
  ["Write with a sense of place", "The manuscript develops in stages, blending evocative detail with readable dialogue and purposeful pacing. Your feedback helps shape the voice, chemistry, and balance of history and romance."],
  ["Refine the details", "Revision strengthens the emotional arc and checks for inconsistencies in the setting, language, and timeline. We agree the depth of historical review and editorial support as part of your project scope."],
];
const faqs = [
  ["How much does historical romance ghostwriting cost?", "The proposal depends on manuscript length, research needs, narrative complexity, and the material you already have. Storybound House will discuss your goals and prepare a tailored scope with clear deliverables and payment terms before work begins."],
  ["How long does a historical romance novel take?", "Historical research adds a development stage alongside outlining, drafting, and revision. We agree a realistic timeline after reviewing your setting, target length, and availability for feedback. Multiple timelines or unfamiliar historical settings may need additional research."],
  ["Which historical periods can we explore?", "Your project can draw on settings such as Regency or Victorian Britain, medieval Europe, the Highland regions, the American frontier, or the World War eras. Tell us the period and place you have in mind so we can discuss the research and writing support it needs."],
  ["How do you approach historical accuracy?", "We use research to guide the outline and draft, then review details such as social conventions, language, travel, and technology for consistency with the chosen period. Any specialist historical review and the treatment of deliberate creative departures can be agreed in your project scope."],
  ["Will I retain ownership of my book?", "Your manuscript is developed for you to publish under your name. Copyright, confidentiality, and the handover of project materials are set out in your agreement, giving you the opportunity to review the terms before the collaboration begins."],
  ["Can the story be traditional, sensual, or somewhere in between?", "Yes. We discuss your intended audience, preferred tone, and comfort with intimacy at the start. Whether you envision a gentle courtship or a more passionate relationship, the romantic pacing and emotional journey are shaped around your direction."],
];

export function HistoricalRomanceOverview() {
  return (
    <div className="romanceContent historicalContent">
      <section className="romanceIntro romanceWrap" aria-labelledby="historical-intro-title">
        <div><p className="eyebrow">History gives it a world. Love gives it a heartbeat.</p><h2 id="historical-intro-title">Rooted in the past.<br /><em>Alive with feeling.</em></h2><p className="romanceLead">A compelling period romance makes another time feel close—and its love story feel deeply human.</p><p>At Storybound House, we bring thoughtful research and emotional storytelling together. From a quiet courtship to a sweeping saga, we help shape a novel in which the setting influences every choice without overwhelming the relationship at its heart.</p><p>The details matter: a form of address, a journey’s length, or the expectations placed on a character can change the direction of a scene. We build those details into your story with care, preserving your voice and keeping readers immersed.</p><Link className="fictionTextLink" href="/contact">Tell us about your period novel <ArrowRight size={17} /></Link></div>
        <aside className="romanceCraft"><Feather size={30} strokeWidth={1.3} aria-hidden="true" /><p className="eyebrow">The art of historical romance</p><h3>A convincing world.<br />An unforgettable connection.</h3>{[["A setting that shapes the story", "Customs, class, and circumstance create meaningful choices for your characters."], ["Chemistry beyond the costumes", "Personal desires and vulnerabilities give the romance its emotional depth."], ["Detail with purpose", "Research supports the action, atmosphere, and tension of each scene."]].map(([title, text]) => <div className="romanceCraftPoint" key={title}><Check size={18} aria-hidden="true" /><div><h4>{title}</h4><p>{text}</p></div></div>)}</aside>
      </section>

      <section className="romanceSpecialties" aria-labelledby="historical-eras-title"><div className="romanceWrap"><div className="romanceSectionHeading"><p className="eyebrow">A different era. An enduring emotion.</p><h2 id="historical-eras-title">Where will your love story unfold?</h2><p>Each period offers its own possibilities for conflict, connection, and a richly imagined world.</p></div><div className="historicalEraGrid">{eras.map(([number, title, text]) => <article key={title}><span aria-hidden="true">{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="romanceProcess romanceWrap" aria-labelledby="historical-process-title"><div className="romanceSectionHeading"><p className="eyebrow">Blending history and heart</p><h2 id="historical-process-title">From a moment in history<br />to a manuscript of your own.</h2><p>A collaborative process brings the historical setting and the emotional journey into focus, one stage at a time.</p></div><ol className="romanceSteps">{process.map(([title, text], index) => <li key={title}><span className="romanceStepNumber" aria-hidden="true">0{index + 1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>

      <section className="historicalReader romanceWrap" aria-labelledby="historical-reader-title"><div><p className="eyebrow">Written for your readers</p><h2 id="historical-reader-title">The atmosphere of another age.<br /><em>The pull of a great romance.</em></h2></div><div><p>Readers may arrive for the setting, but believable chemistry, meaningful stakes, and an earned resolution keep them invested. We help define the audience, tone, and level of intimacy that suit your vision, from traditional courtship to a more passionate love story.</p><p>Your characters’ dialogue and inner lives should feel at home in their world while remaining accessible to readers. Through ongoing reviews, we work with you to find that balance and give the story a voice that feels like yours.</p></div></section>

      <section className="romanceInvestment romanceWrap" aria-labelledby="historical-partnership-title"><div><p className="eyebrow">A clear, considered partnership</p><h2 id="historical-partnership-title">Your vision.<br /><em>Our shared attention to craft.</em></h2><p>Research, writing, and revision all contribute to the scope of a historical novel. We discuss what your book needs and prepare a proposal around its length, complexity, and publishing goals.</p><Link className="button" href="/contact">Discuss your manuscript <ArrowRight size={17} /></Link></div><div className="romanceScope"><h3>Clarity from the beginning</h3><ul>{["Research and editorial support defined in your scope", "A writing schedule with opportunities for your feedback", "Confidentiality terms set out in your agreement", "Clear ownership and manuscript handover terms", "A tailored proposal with agreed deliverables"].map(text => <li key={text}><Check size={18} aria-hidden="true" />{text}</li>)}</ul></div></section>

      <section className="romanceFaq romanceWrap" aria-labelledby="historical-faq-title"><div><p className="eyebrow">Your questions, answered</p><h2 id="historical-faq-title">Before your story<br /><em>takes us back in time.</em></h2><p>A few things to know about developing your historical romance with Storybound House.</p></div><div className="romanceQuestions">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<Plus size={18} aria-hidden="true" /></summary><p>{answer}</p></details>)}</div></section>
      <section className="romanceClosing"><p className="eyebrow">Your next chapter begins here</p><h2>Give your vision of the past a voice.</h2><p>Share your setting, your characters, or the first spark of an idea.</p><Link className="button" href="/contact">Let’s shape your story <ArrowRight size={17} /></Link></section>
    </div>
  );
}
