import Link from "next/link";
import { ArrowRight, Check, Moon, Plus } from "lucide-react";

const specialties = [
  ["01", "Urban fantasy romance", "Hidden magic, supernatural communities, and contemporary city life create a vivid backdrop for action and attraction."],
  ["02", "Vampire & shifter romance", "Immortal lives, pack loyalties, and supernatural bonds bring questions of belonging, power, and choice into the relationship."],
  ["03", "Fae & mythological romance", "Ancient bargains, otherworldly courts, and intricate magical traditions shape love stories with far-reaching consequences."],
  ["04", "Dark paranormal romance", "Morally complex adult characters and dangerous worlds heighten the tension, with tone, boundaries, and emotional direction established together."],
];
const steps = [
  ["Establish the lore", "We explore your world’s inhabitants, hierarchies, magical limits, and relationship bonds. A shared reference for the lore helps keep the story consistent as the manuscript grows."],
  ["Connect love and conflict", "Together, we outline the characters’ emotional journey alongside the supernatural stakes. Romantic turning points and external threats develop in step, giving each a meaningful effect on the other."],
  ["Draft for immersion", "The manuscript takes shape in stages, balancing atmosphere, action, and intimacy. You review chapters and share feedback on the voice, chemistry, and unfolding world."],
  ["Review the whole world", "Revision checks the continuity of the lore, character motivations, pacing, and emotional payoff. We agree the depth of developmental and copy editing as part of your project scope."],
];
const faqs = [
  ["How much does paranormal romance ghostwriting cost?", "The proposal depends on your target length, world-building complexity, research needs, and existing material. Storybound House prepares a tailored scope with clear deliverables and payment terms after discussing your concept and the support it needs."],
  ["How long does a supernatural romance novel take?", "Building the lore takes time alongside outlining, drafting, and revision. We establish a realistic schedule based on the complexity of your world, manuscript length, and opportunities for your feedback. A series or an entirely new magical system may require more development."],
  ["How do you keep the magic and the romance consistent?", "We establish the world’s rules and relationship arc before drafting, then refer back to them during chapter development and revision. A shared lore reference helps track magical limitations, histories, and character choices as the story unfolds."],
  ["Can the project be shaped around my budget?", "We can discuss your priorities and define the support your manuscript needs most. The proposal makes the writing, development, and editorial scope clear so you can assess the investment before committing."],
  ["Can I choose the level of romantic intimacy?", "Yes. We discuss your intended adult audience, tone, and boundaries at the start. Whether you prefer a closed-door relationship, a slow burn, or a more sensual romance, the intimacy should serve the characters and their emotional journey."],
  ["Will I retain ownership of my book?", "Your manuscript is developed for you to publish under your name. Ownership, confidentiality, and the handover of materials are set out in your project agreement, so you can review the terms before work begins."],
  ["Can we create original supernatural beings or lore?", "Absolutely. Your world can draw on familiar mythology or introduce something entirely your own. We help define the origins, abilities, limitations, and social structures that make your creations believable within the story."],
];

export function ParanormalRomanceOverview() {
  return (
    <div className="romanceContent">
      <section className="romanceIntro romanceWrap" aria-labelledby="paranormal-intro-title"><div><p className="eyebrow">Where the impossible feels personal</p><h2 id="paranormal-intro-title">An extraordinary world.<br /><em>A deeply human connection.</em></h2><p className="romanceLead">Magic draws readers into your world. A love worth believing in keeps them there.</p><p>At Storybound House, we bring imaginative world-building and emotional storytelling together. Whether your characters are human, immortal, or something entirely new, we help shape a paranormal romance around your voice and vision.</p><p>The supernatural elements should do more than decorate the setting. A dangerous gift, an ancient allegiance, or a bond neither character understands can change what love asks of them—and make every choice matter.</p><Link className="fictionTextLink" href="/contact">Share your supernatural story <ArrowRight size={17} /></Link></div><aside className="romanceCraft"><Moon size={30} strokeWidth={1.3} aria-hidden="true" /><p className="eyebrow">Two journeys. One story.</p><h3>Let the magic deepen<br />the connection.</h3>{[["A world with clear rules", "Abilities, limitations, and consequences that make the extraordinary feel believable."], ["An emotional arc with purpose", "Attraction, vulnerability, and trust that develop alongside the supernatural stakes."], ["Conflict that brings both together", "World-building that challenges the relationship and shapes the choices ahead."]].map(([title, text]) => <div className="romanceCraftPoint" key={title}><Check size={18} aria-hidden="true" /><div><h4>{title}</h4><p>{text}</p></div></div>)}</aside></section>

      <section className="romanceSpecialties" aria-labelledby="paranormal-specialties-title"><div className="romanceWrap"><div className="romanceSectionHeading"><p className="eyebrow">Find your world beyond the ordinary</p><h2 id="paranormal-specialties-title">Many kinds of magic.<br />Endless possibilities for love.</h2><p>We develop the lore, atmosphere, and relationship around the paranormal story you want to tell.</p></div><div className="historicalEraGrid paranormalSpecialtyGrid">{specialties.map(([number, title, text]) => <article key={title}><span aria-hidden="true">{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="romanceProcess romanceWrap" aria-labelledby="paranormal-process-title"><div className="romanceSectionHeading"><p className="eyebrow">From lore to love story</p><h2 id="paranormal-process-title">Build the world.<br />Bring the relationship to life.</h2><p>A structured collaboration keeps the fantastical details and emotional journey connected at every stage.</p></div><ol className="romanceSteps">{steps.map(([title, text], index) => <li key={title}><span className="romanceStepNumber" aria-hidden="true">0{index + 1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>

      <section className="historicalReader romanceWrap" aria-labelledby="paranormal-chemistry-title"><div><p className="eyebrow">Chemistry as believable as the magic</p><h2 id="paranormal-chemistry-title">Supernatural power.<br /><em>Personal vulnerability.</em></h2></div><div><p>Even an immortal character has something to lose. We explore the fears, desires, and vulnerabilities beneath extraordinary abilities, giving each character an inner life that makes the relationship compelling.</p><p>Your preferred tone and level of intimacy guide the writing. From a gentle slow burn to a more passionate adult romance, we work with you to balance tension, power dynamics, and emotional connection.</p></div></section>

      <section className="romanceInvestment romanceWrap" aria-labelledby="paranormal-investment-title"><div><p className="eyebrow">A clear scope for an expansive world</p><h2 id="paranormal-investment-title">Imagination without limits.<br /><em>A plan with clarity.</em></h2><p>Your world’s complexity, manuscript length, and starting point shape the work involved. We prepare a tailored proposal that sets out the development, writing, and editorial support your story needs.</p><Link className="button" href="/contact">Discuss your project <ArrowRight size={17} /></Link></div><div className="romanceScope"><h3>What we’ll define together</h3><ul>{["World-building, lore, and research requirements", "Standalone or series development needs", "Chapter reviews and revision support", "Project schedule, deliverables, and payment terms", "Confidentiality and manuscript ownership terms"].map(text => <li key={text}><Check size={18} aria-hidden="true" />{text}</li>)}</ul></div></section>

      <section className="romanceFaq romanceWrap" aria-labelledby="paranormal-faq-title"><div><p className="eyebrow">Before we enter your world</p><h2 id="paranormal-faq-title">A little clarity.<br /><em>A lot of possibility.</em></h2><p>Answers to common questions about developing a paranormal romance with Storybound House.</p></div><div className="romanceQuestions">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<Plus size={18} aria-hidden="true" /></summary><p>{answer}</p></details>)}</div></section>
      <section className="romanceClosing"><p className="eyebrow">Your imagination is the beginning</p><h2>Give your supernatural love story a voice.</h2><p>Bring your characters, your lore, or the first spark of an impossible connection.</p><Link className="button" href="/contact">Let’s build your story <ArrowRight size={17} /></Link></section>
    </div>
  );
}
